[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NITRO_PRESET = "netlify"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' data: blob:; img-src 'self' data: https: blob:; media-src 'self' data: https: blob:;"

[[headers]]
  for = "/_server/*"
  [headers.values]
    Access-Control-Allow-Origin = "self"
    Access-Control-Allow-Methods = "POST"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

